# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    restoreDirectory: '$(System.DefaultWorkingDirectory)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd '$(System.DefaultWorkingDirectory)'
      dir
    workingDirectory: '$(Build.ArtifactStagingDirectory)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    packDirectory: '$(System.DefaultWorkingDirectory)'
    versioningScheme: 'off'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd '$(System.DefaultWorkingDirectory)'
      dir
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'a37867b6-426c-4eaa-a860-369136c21af0/885f3815-a47b-49d6-8a02-80b13b83f522'








