# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


jobs:
- deployment: VMDeploy
  displayName: web
  pool:
    vmImage: 'windows-latest'
  environment:
    name:  env01
    resourceType: VirtualMachine
    tags: web
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment
        - script: mkdir app
        - script: echo hello>>test.txt
